services:
  postgres:
    image: postgres:17-bookworm
    container_name: lab_groupware
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '2344:5432'
    environment:
      POSTGRES_USER: lab_groupware
      POSTGRES_PASSWORD: kr+G&d=I&%xvTdfXS6@s
      POSTGRES_DB: postgres
