// 서버 프로토콜 -> http / https
export const ENV_PROTOCOL_KEY = 'PROTOCOL';
export const ENV_HOST_KEY = 'HOST';

//SECTION - jwt
export const ENV_JWT_SECRET_KEY = 'JWT_SECRET';
export const ENV_JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET';
export const ENV_HASH_ROUNDS_KEY = 'HASH_ROUND';
export const ENV_JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME';
export const ENV_JWT_REFRESH_EXPIRATION_TIME = 'JWT_REFRESH_EXPIRATION_TIME';
//!SECTION

//SECTION - Postgres
export const ENV_DB_HOST_KEY = 'DB_HOST';
export const ENV_DB_PORT_KEY = 'DB_PORT';
export const ENV_DB_USER_KEY = 'DB_USERNAME';
export const ENV_DB_PASSWORD_KEY = 'DB_PASSWORD';
export const ENV_DB_DATABASE_KEY = 'DB_DATABASE';
//!SECTION

//SECTION - Redis
export const ENV_REDIS_HOST = 'REDIS_HOST';
export const ENV_REDIS_PORT = 'REDIS_PORT';
export const ENV_REDIS_PASSWORD = 'REDIS_PASSWORD';
//!SECTION

export const ENV_KAKAO_CLIENT_ID = 'KAKAO_CLIENT_ID';
export const ENV_REDIRECT_URI = 'REDIRECT_URI';

export const ENV_NAVER_CLINET_ID = 'NAVER_CLIENT_ID';
export const ENV_NAVER_API_KEY = 'NAVER_API_KEY';
